/**
 * Copyright (c) 1998-2011 Zap Informática, Inc. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Zap
 * Informática, Inc. ("Confidential Information"). You shall not disclose such
 * Confidential Information and shall use it only in accordance with the terms
 * of the license agreement you entered into with Zap Informática.
 */
package br.com.estatistica.tela.principal;

import br.com.estatistica.modelo.Usuario;
import br.com.estatistica.tela.cadastro.FUsuarios;
import br.com.estatistica.tela.calculo.FBinomial;
import br.com.estatistica.tela.calculo.FExponencial;
import br.com.estatistica.tela.calculo.FNormal;
import br.com.estatistica.tela.calculo.FPoisson;
import br.com.estatistica.tela.calculo.FUniforme;
import br.com.util.Util;
import com.zap.arca.LoggerEx;
import com.zap.arca.util.WindowUtils;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 * @version 1.00, 20 Dezembro 2010
 * @author Edidelson
 * @since V1
 */
public class FPrincipal extends javax.swing.JFrame {

    Util util = new Util();
    private BufferedImage image;
    Usuario usuario;

    // Bloco de inicialização que aplica o ícone da aplicação
    {
        util.inserirIconeAplicacao(this);
    }

    {
        try {
            image = ImageIO.read(getClass().getResourceAsStream("/resources/imagens/fundo-hd.png"));
        } catch (IOException ex) {
            LoggerEx.log(ex);
        }
    }

    /**
     * Creates new form Principal
     */
    public FPrincipal(Usuario usuario) {
        WindowUtils.setSystemLookAndFeel();
        initComponents();
        setTitle("Estatística");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        iniciar();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgButtonPrincipal = new javax.swing.ButtonGroup();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        imPanel = new org.jdesktop.swingx.JXImagePanel();
        lbLicenciadoPara = new javax.swing.JLabel();
        tbAtalhos = new javax.swing.JToolBar();
        btSair = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbUsuarioLogado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbDataAtual = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miBackup = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCalculadora = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuBinomial = new javax.swing.JMenuItem();
        menuPoisson = new javax.swing.JMenuItem();
        menuNormal = new javax.swing.JMenuItem();
        menuExponencial = new javax.swing.JMenuItem();
        menuUniforme = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("framePrincipal"); // NOI18N

        imPanel.setDefaultImage(null);

        lbLicenciadoPara.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        tbAtalhos.setBackground(new java.awt.Color(213, 220, 226));
        tbAtalhos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tbAtalhos.setFloatable(false);
        tbAtalhos.setRollover(true);

        btSair.setBackground(new java.awt.Color(213, 220, 226));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/lockstart_session.png"))); // NOI18N
        btSair.setToolTipText("Sair...");
        btSair.setFocusable(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        tbAtalhos.add(btSair);

        javax.swing.GroupLayout imPanelLayout = new javax.swing.GroupLayout(imPanel);
        imPanel.setLayout(imPanelLayout);
        imPanelLayout.setHorizontalGroup(
            imPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbAtalhos, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLicenciadoPara, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        imPanelLayout.setVerticalGroup(
            imPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imPanelLayout.createSequentialGroup()
                .addComponent(tbAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 486, Short.MAX_VALUE)
                .addComponent(lbLicenciadoPara, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("Usuário:");

        lbUsuarioLogado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbUsuarioLogado.setText("Administrador");

        jLabel4.setText("Data:");

        lbDataAtual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDataAtual.setText("jLabel5");

        mnArquivo.setMnemonic('A');
        mnArquivo.setText("Arquivo");

        miBackup.setText("Backup...");
        miBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBackupActionPerformed(evt);
            }
        });
        mnArquivo.add(miBackup);
        mnArquivo.add(jSeparator1);

        miSair.setText("Sair...");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mnArquivo.add(miSair);

        mbPrincipal.add(mnArquivo);

        jMenu1.setText("Cálculos");

        menuUsuario.setText("Usuário...");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuario);
        jMenu1.add(jSeparator2);

        menuCalculadora.setText("Calculadora...");
        menuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalculadoraActionPerformed(evt);
            }
        });
        jMenu1.add(menuCalculadora);
        jMenu1.add(jSeparator3);

        menuBinomial.setText("Binomial...");
        menuBinomial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBinomialActionPerformed(evt);
            }
        });
        jMenu1.add(menuBinomial);

        menuPoisson.setText("Poisson...");
        menuPoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPoissonActionPerformed(evt);
            }
        });
        jMenu1.add(menuPoisson);

        menuNormal.setText("Normal...");
        menuNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNormalActionPerformed(evt);
            }
        });
        jMenu1.add(menuNormal);

        menuExponencial.setText("Exponencial...");
        menuExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExponencialActionPerformed(evt);
            }
        });
        jMenu1.add(menuExponencial);

        menuUniforme.setText("Uniforme...");
        menuUniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUniformeActionPerformed(evt);
            }
        });
        jMenu1.add(menuUniforme);

        mbPrincipal.add(jMenu1);

        jMenu2.setText("Ajuda");

        menuSobre.setText("Sobre...");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        jMenu2.add(menuSobre);

        mbPrincipal.add(jMenu2);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator20, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(583, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(imPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataAtual)
                    .addComponent(lbUsuarioLogado)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_miSairActionPerformed

    private void miBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBackupActionPerformed
        new FBackup().setVisible(true);
    }//GEN-LAST:event_miBackupActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void menuBinomialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBinomialActionPerformed
        new FBinomial().setVisible(true);
    }//GEN-LAST:event_menuBinomialActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        new FUsuarios().setVisible(true);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuPoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPoissonActionPerformed
        new FPoisson().setVisible(true);
    }//GEN-LAST:event_menuPoissonActionPerformed

    private void menuNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNormalActionPerformed
        new FNormal().setVisible(true);
    }//GEN-LAST:event_menuNormalActionPerformed

    private void menuExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExponencialActionPerformed
        new FExponencial().setVisible(true);
    }//GEN-LAST:event_menuExponencialActionPerformed

    private void menuUniformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUniformeActionPerformed
        new FUniforme().setVisible(true);
    }//GEN-LAST:event_menuUniformeActionPerformed

    private void menuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalculadoraActionPerformed
        try {
            Runtime.getRuntime().exec("calc.exe");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuCalculadoraActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        new DSobreSistema(this, true).setVisible(true); 
    }//GEN-LAST:event_menuSobreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgButtonPrincipal;
    private javax.swing.JButton btSair;
    private org.jdesktop.swingx.JXImagePanel imPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lbDataAtual;
    private javax.swing.JLabel lbLicenciadoPara;
    private javax.swing.JLabel lbUsuarioLogado;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem menuBinomial;
    private javax.swing.JMenuItem menuCalculadora;
    private javax.swing.JMenuItem menuExponencial;
    private javax.swing.JMenuItem menuNormal;
    private javax.swing.JMenuItem menuPoisson;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenuItem menuUniforme;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JMenuItem miBackup;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JToolBar tbAtalhos;
    // End of variables declaration//GEN-END:variables

    public void iniciar() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        lbDataAtual.setText(df.format(new java.util.Date()));
        if (usuario != null) {
            lbUsuarioLogado.setText(usuario.getApelido());
        }
    }
}
