package br.com.estatistica.tela.calculo;

import br.com.estatistica.dao.DAONormal;
import br.com.estatistica.modelo.IModelo;
import br.com.estatistica.modelo.Normal;
import br.com.estatistica.tela.generico.FrameGenerico;
import br.com.estatistica.tela.principal.DSobreSistema;
import br.com.estatistica.tela.tablemodel.NormalTableModel;
import com.zap.arca.LoggerEx;
import com.zap.arca.util.WindowUtils;
import java.awt.Component;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.commons.math3.distribution.NormalDistribution;

/**
 * @author Edidelson
 */
public class FNormal extends FrameGenerico {

    private NormalTableModel normalTableModel = new NormalTableModel();
    private Normal normal;

    public FNormal() {
        initComponents();
        setLocationRelativeTo(null);
        iniciar();
        actionMenu(INCLUSAO);
        tfProbabilidade.setTotalCasas(5, 7);
    }

    @Override
    public void limparCampos() {
        super.limparCampos();
        exibirDados(dao, tbNormal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEditar = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btgNormal = new javax.swing.ButtonGroup();
        tbAtalhos = new javax.swing.JToolBar();
        tbIncluir = new javax.swing.JToggleButton();
        tbAlterar = new javax.swing.JToggleButton();
        tbExcluir = new javax.swing.JToggleButton();
        spBar = new javax.swing.JToolBar.Separator();
        tbPesquisar = new javax.swing.JToggleButton();
        tbFiltrar = new javax.swing.JToggleButton();
        tbCalculadora = new javax.swing.JToggleButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNormal = new com.zap.arca.JATable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        plBotoes = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        plCampos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        tfCodigo = new com.zap.arca.JATextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfMedia = new com.zap.arca.JADecimalFormatField();
        tfDesvioPadrao = new com.zap.arca.JADecimalFormatField();
        tfVariavelA = new com.zap.arca.JADecimalFormatField();
        tfVariavelB = new com.zap.arca.JADecimalFormatField();
        tfProbabilidade = new com.zap.arca.JADecimalFormatField();
        jLabel3 = new javax.swing.JLabel();
        cbCondicao = new javax.swing.JComboBox();
        tfPercentual = new com.zap.arca.JADecimalFormatField();
        jLabel8 = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miArquivoSair = new com.zap.arca.JAMenuItem();
        mnEditar = new javax.swing.JMenu();
        miEdiIncluir = new javax.swing.JMenuItem();
        miEdiAlterar = new javax.swing.JMenuItem();
        miEdiExcluir = new javax.swing.JMenuItem();
        miEditarLimpar = new com.zap.arca.JAMenuItem();
        mnExibir = new javax.swing.JMenu();
        miExibirAtualizar = new com.zap.arca.JAMenuItem();
        spExibir = new javax.swing.JPopupMenu.Separator();
        miExibirFiltro = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        miAjudaSobre = new com.zap.arca.JAMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Normal");

        tbAtalhos.setFloatable(false);
        tbAtalhos.setRollover(true);

        bgEditar.add(tbIncluir);
        tbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/add.png"))); // NOI18N
        tbIncluir.setToolTipText("Incluir");
        tbIncluir.setFocusable(false);
        tbIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIncluirActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbIncluir);

        bgEditar.add(tbAlterar);
        tbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/edit.png"))); // NOI18N
        tbAlterar.setToolTipText("Alterar");
        tbAlterar.setFocusable(false);
        tbAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAlterarActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbAlterar);

        bgEditar.add(tbExcluir);
        tbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/delete.png"))); // NOI18N
        tbExcluir.setFocusable(false);
        tbExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExcluirActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbExcluir);
        tbAtalhos.add(spBar);

        bgEditar.add(tbPesquisar);
        tbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/pesquisar.png"))); // NOI18N
        tbPesquisar.setFocusable(false);
        tbPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPesquisarActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbPesquisar);

        bgEditar.add(tbFiltrar);
        tbFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/filter.png"))); // NOI18N
        tbFiltrar.setFocusable(false);
        tbFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbFiltrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFiltrarActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbFiltrar);

        tbCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/calculator.png"))); // NOI18N
        tbCalculadora.setToolTipText("Calculadora");
        tbCalculadora.setFocusable(false);
        tbCalculadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbCalculadora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCalculadoraActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbCalculadora);

        jSplitPane1.setDividerLocation(110);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tbNormal.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbNormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbNormal);
        tbNormal.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                alterar(tbNormal);
            }
        });

        jSplitPane1.setTopComponent(jScrollPane1);

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 300));

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plBotoesLayout = new javax.swing.GroupLayout(plBotoes);
        plBotoes.setLayout(plBotoesLayout);
        plBotoesLayout.setHorizontalGroup(
            plBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plBotoesLayout.createSequentialGroup()
                .addContainerGap(550, Short.MAX_VALUE)
                .addComponent(btOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancelar)
                .addGap(0, 0, 0))
        );

        plBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCancelar, btOk});

        plBotoesLayout.setVerticalGroup(
            plBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btOk)
                .addComponent(btCancelar))
        );

        plCampos.setBackground(new java.awt.Color(255, 255, 255));
        plCampos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fórmula"));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/normal.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        lbCodigo.setText("Código:");

        tfCodigo.setEnabled(false);

        jLabel1.setText("Média ( µ ):");

        jLabel4.setText("Desvio Padrão ( s ):");

        jLabel5.setText("Variável ( A ):");

        jLabel6.setText("Variável ( B ):");

        btCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btCalcular.setText("Calcular!");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        jLabel7.setText("Probabilidade:");

        tfMedia.setName("Média"); // NOI18N

        tfDesvioPadrao.setName("Desvio Padrão"); // NOI18N

        tfVariavelA.setName("Variável (A)"); // NOI18N

        tfVariavelB.setEnabled(false);

        tfProbabilidade.setEnabled(false);
        tfProbabilidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setText("Condição:");

        cbCondicao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCondicaoItemStateChanged(evt);
            }
        });

        tfPercentual.setEnabled(false);
        tfPercentual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setText("Percentual:");

        javax.swing.GroupLayout plCamposLayout = new javax.swing.GroupLayout(plCampos);
        plCampos.setLayout(plCamposLayout);
        plCamposLayout.setHorizontalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(lbCodigo)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbCondicao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfMedia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfDesvioPadrao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfVariavelA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfVariavelB, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfProbabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        plCamposLayout.setVerticalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plCamposLayout.createSequentialGroup()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDesvioPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfVariavelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfVariavelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfProbabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addComponent(tfPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCalcular)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tfCodigo.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                // verificaAlteracao();
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
            public void changedUpdate(DocumentEvent e) { }
            public void removeUpdate(DocumentEvent e) {
                //verificaAlteracao();
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
        });

        jTabbedPane1.addTab("Normal", plCampos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        jSplitPane1.setBottomComponent(jScrollPane2);

        mnArquivo.setText("Arquivo");

        miArquivoSair.setText("Sair");
        miArquivoSair.setPreferredSize(new java.awt.Dimension(120, 22));
        miArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miArquivoSairActionPerformed(evt);
            }
        });
        mnArquivo.add(miArquivoSair);

        mbPrincipal.add(mnArquivo);

        mnEditar.setText("Editar");

        miEdiIncluir.setText("Incluir");
        miEdiIncluir.setPreferredSize(new java.awt.Dimension(120, 22));
        miEdiIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEdiIncluirActionPerformed(evt);
            }
        });
        mnEditar.add(miEdiIncluir);

        miEdiAlterar.setText("Alterar");
        miEdiAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEdiAlterarActionPerformed(evt);
            }
        });
        mnEditar.add(miEdiAlterar);

        miEdiExcluir.setText("Excluir");
        miEdiExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEdiExcluirActionPerformed(evt);
            }
        });
        mnEditar.add(miEdiExcluir);

        miEditarLimpar.setText("Limpar");
        miEditarLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarLimparActionPerformed(evt);
            }
        });
        mnEditar.add(miEditarLimpar);

        mbPrincipal.add(mnEditar);

        mnExibir.setText("Exibir");

        miExibirAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        miExibirAtualizar.setText("Atualizar");
        miExibirAtualizar.setPreferredSize(new java.awt.Dimension(150, 22));
        miExibirAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExibirAtualizarActionPerformed(evt);
            }
        });
        mnExibir.add(miExibirAtualizar);
        mnExibir.add(spExibir);

        miExibirFiltro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        miExibirFiltro.setText("Filtro...");
        miExibirFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExibirFiltroActionPerformed(evt);
            }
        });
        mnExibir.add(miExibirFiltro);

        mbPrincipal.add(mnExibir);

        mnAjuda.setText("Ajuda");

        miAjudaSobre.setText("Sobre...");
        miAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjudaSobreActionPerformed(evt);
            }
        });
        mnAjuda.add(miAjudaSobre);

        mbPrincipal.add(mnAjuda);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void tbIncluirActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_tbIncluirActionPerformed
        actionMenu(INCLUSAO);
     }//GEN-LAST:event_tbIncluirActionPerformed

    private void tbAlterarActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_tbAlterarActionPerformed
        actionMenu(ALTERACAO);
     }//GEN-LAST:event_tbAlterarActionPerformed

    private void miArquivoSairActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miArquivoSairActionPerformed
        this.dispose();
     }//GEN-LAST:event_miArquivoSairActionPerformed

    private void miEdiIncluirActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEdiIncluirActionPerformed
        actionMenu(INCLUSAO);
     }//GEN-LAST:event_miEdiIncluirActionPerformed

    private void miEdiAlterarActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEdiAlterarActionPerformed
        actionMenu(ALTERACAO);
     }//GEN-LAST:event_miEdiAlterarActionPerformed

    private void miEdiExcluirActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEdiExcluirActionPerformed
        actionMenu(EXCLUSAO);
     }//GEN-LAST:event_miEdiExcluirActionPerformed

    private void miExibirAtualizarActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miExibirAtualizarActionPerformed
        actionMenu(LIMPAR);
     }//GEN-LAST:event_miExibirAtualizarActionPerformed

    private void miExibirFiltroActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miExibirFiltroActionPerformed
        actionMenu(FILTRAR);
     }//GEN-LAST:event_miExibirFiltroActionPerformed

    private void miEditarLimparActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEditarLimparActionPerformed
        actionMenu(LIMPAR);
    }//GEN-LAST:event_miEditarLimparActionPerformed

    private void miAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjudaSobreActionPerformed
        new DSobreSistema(this, true).setVisible(true); 
    }//GEN-LAST:event_miAjudaSobreActionPerformed

    private void tbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExcluirActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_tbExcluirActionPerformed

    private void tbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPesquisarActionPerformed
        actionMenu(PESQUISAR);
    }//GEN-LAST:event_tbPesquisarActionPerformed

    private void tbFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFiltrarActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_tbFiltrarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if (verificarCampos(camposVerificar)) {
            inserirOuAlterar();
            limparCampos();
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        if (validarCampos() && verificarCampos(camposVerificar)) { 
            tfProbabilidade.setValue(calcular());
            tfPercentual.setValue(calcular().multiply(new BigDecimal(100))); 
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void cbCondicaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCondicaoItemStateChanged
        if (cbCondicao.getSelectedIndex() == 3) {
            tfVariavelB.setEnabled(true);
        } else {
            tfVariavelB.setEnabled(false);
        }
    }//GEN-LAST:event_cbCondicaoItemStateChanged

    private void tbCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCalculadoraActionPerformed
        try {
            Runtime.getRuntime().exec("calc.exe");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tbCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNormal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEditar;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btOk;
    private javax.swing.ButtonGroup btgNormal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbCondicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JMenuBar mbPrincipal;
    private com.zap.arca.JAMenuItem miAjudaSobre;
    private com.zap.arca.JAMenuItem miArquivoSair;
    private javax.swing.JMenuItem miEdiAlterar;
    private javax.swing.JMenuItem miEdiExcluir;
    private javax.swing.JMenuItem miEdiIncluir;
    private com.zap.arca.JAMenuItem miEditarLimpar;
    private com.zap.arca.JAMenuItem miExibirAtualizar;
    private javax.swing.JMenuItem miExibirFiltro;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnEditar;
    private javax.swing.JMenu mnExibir;
    private javax.swing.JPanel plBotoes;
    private javax.swing.JPanel plCampos;
    private javax.swing.JToolBar.Separator spBar;
    private javax.swing.JPopupMenu.Separator spExibir;
    private javax.swing.JToggleButton tbAlterar;
    private javax.swing.JToolBar tbAtalhos;
    private javax.swing.JToggleButton tbCalculadora;
    private javax.swing.JToggleButton tbExcluir;
    private javax.swing.JToggleButton tbFiltrar;
    private javax.swing.JToggleButton tbIncluir;
    private com.zap.arca.JATable tbNormal;
    private javax.swing.JToggleButton tbPesquisar;
    private com.zap.arca.JATextField tfCodigo;
    private com.zap.arca.JADecimalFormatField tfDesvioPadrao;
    private com.zap.arca.JADecimalFormatField tfMedia;
    private com.zap.arca.JADecimalFormatField tfPercentual;
    private com.zap.arca.JADecimalFormatField tfProbabilidade;
    private com.zap.arca.JADecimalFormatField tfVariavelA;
    private com.zap.arca.JADecimalFormatField tfVariavelB;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciar() {
        dao = new DAONormal();

        tbPrincipal = tbNormal;
        toggleButton = tbIncluir;
        ctChave = tfCodigo;

        tbNormal.setName("TB_FPOISSON");
        tbNormal.setModel(normalTableModel);

        camposVerificar = new Component[]{tfMedia, tfDesvioPadrao, tfVariavelA};
        camposLimpar = new Component[]{tfMedia, tfCodigo, tfDesvioPadrao,
            tfVariavelA, tfVariavelB, tfProbabilidade, tfPercentual};

        WindowUtils.nextEnter(plCampos);
        WindowUtils.exitEsc(this);
        configurarSincronizacao(dao, tbNormal);
        for (Normal.Condicao condicao : Normal.Condicao.values()) {
            cbCondicao.addItem(condicao);
        }
    }

    public Normal.Condicao getCondicao() {
        if (cbCondicao.getSelectedIndex() == 0) {
            return Normal.Condicao.MAIOR;
        } else if (cbCondicao.getSelectedIndex() == 1) {
            return Normal.Condicao.MENOR;
        } else {
            return Normal.Condicao.ENTRE;
        }
    }

    @Override
    public void inserirOuAlterar() {
        normal = new Normal();
        normal.setDesvioPadrao(tfDesvioPadrao.getValue().doubleValue());
        normal.setMedia(tfMedia.getValue().doubleValue());
        normal.setResultado(new BigDecimal(tfProbabilidade.getValue().doubleValue()));
        normal.setVariavelA(tfVariavelA.getValue().doubleValue());
        normal.setVariavelB(tfVariavelB.getValue().doubleValue());
        normal.setCondicao(getCondicao());
        try {
            if (tbAlterar.isSelected()) {
                normal.setCodigo(Integer.valueOf(tfCodigo.getText()));
                dao.alterar(normal);
            } else {
                dao.adicionar(normal);
            }
        } catch (RuntimeException ex) {
            LoggerEx.log(ex);
        }
    }

    @Override
    public void preencherCampos(IModelo m) {
        normal = (Normal) m;
        tfCodigo.setText(String.valueOf(normal.getCodigo()));
        tfMedia.setValue(normal.getMedia().doubleValue());
        tfDesvioPadrao.setValue(normal.getDesvioPadrao().doubleValue());
        tfVariavelA.setValue(normal.getVariavelA().doubleValue());
        tfVariavelB.setValue(normal.getVariavelB() != null ? normal.getVariavelB().doubleValue() : BigDecimal.ZERO);
        tfProbabilidade.setValue(normal.getResultado().doubleValue());
        tfPercentual.setValue(normal.getResultado().multiply(new BigDecimal(100))); 
    }

    @Override
    public void preencherTabela(int linha, IModelo i) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public BigDecimal calcular() {
        double desvioPadrao = tfDesvioPadrao.getValue().doubleValue();
        double media = tfMedia.getValue().doubleValue();
        double variavelA = tfVariavelA.getValue().doubleValue();
        double variavelB = tfVariavelB.getValue().doubleValue();
        NormalDistribution distribution = new NormalDistribution(media, desvioPadrao);
        double resultado = 0.00;
        if (cbCondicao.getSelectedIndex() == 0) {
            resultado = 0.5 - distribution.probability(0.00, variavelA);
            if (resultado < 0) {
                resultado *= -1;
            }
            if (media > variavelA) {
                resultado += 0.5;

            } else {
                resultado -= 0.5;
            }
            if (resultado < 0) {
                resultado *= -1;
            }
            return new BigDecimal(resultado);
        } else if (cbCondicao.getSelectedIndex() == 1) {
            resultado = 0.5 - distribution.probability(0.00, variavelA);
            if (resultado < 0) {
                resultado *= -1;
            }
            if (variavelA > media) {
                resultado += 0.5;

            } else if (variavelA < media) {
                resultado -= 0.5;
            }
            if (resultado < 0) {
                resultado *= -1;
            }
            return new BigDecimal(resultado);
        } else if (cbCondicao.getSelectedIndex() == 2) {
            resultado = 0.5 - distribution.probability(variavelA, variavelB);
            if (resultado < 0) {
                resultado *= -1;
            }
            if (variavelA > media && variavelB > media) {
                resultado -= 0.5;
            } else {
                resultado += 0.5;
            }
            if (variavelA < media && variavelB < media) {
                resultado -= 1;
            }
            if (resultado < 0) {
                resultado *= -1;
            }
            return new BigDecimal(resultado);
        }
        return null;
    }

    public boolean validarCampos() {
        if (cbCondicao.getSelectedIndex() == 3) {
            if (tfVariavelA.getValue().doubleValue() > tfVariavelB.getValue().doubleValue()) {
                JOptionPane.showMessageDialog(null, "Variavel A maior que a variavel B");
                tfVariavelA.requestFocus();
                return false;
            }
        }
        return true;
    }
}