package br.com.estatistica.tela.calculo;

import br.com.estatistica.auxiliares.DMedia;
import br.com.estatistica.auxiliares.IValores;
import br.com.estatistica.auxiliares.formulas.Calculo;
import br.com.estatistica.dao.DAOGenerico;
import br.com.estatistica.dao.DAOPoisson;
import br.com.estatistica.modelo.Binomial;
import br.com.estatistica.modelo.IModelo;
import br.com.estatistica.modelo.Poisson;
import br.com.estatistica.tela.generico.FrameGenerico;
import br.com.estatistica.tela.tablemodel.PoissonTableModel;
import com.zap.arca.LoggerEx;
import com.zap.arca.util.WindowUtils;
import java.awt.Component;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sun.nio.cs.ext.Big5;

/**
 * @author Edidelson
 */
public class FPoisson extends FrameGenerico implements IValores {

    private PoissonTableModel poissonTableModel = new PoissonTableModel();
    private Poisson poisson;

    public FPoisson() {
        initComponents();
        setLocationRelativeTo(null);
        iniciar();
        actionMenu(INCLUSAO);
        formatarCampos();
    }

    @Override
    public boolean verificarCampos(Component[] components) {
        if (!super.verificarCampos(components)) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEditar = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tbAtalhos = new javax.swing.JToolBar();
        tbIncluir = new javax.swing.JToggleButton();
        tbAlterar = new javax.swing.JToggleButton();
        tbExcluir = new javax.swing.JToggleButton();
        spBar = new javax.swing.JToolBar.Separator();
        tbPesquisar = new javax.swing.JToggleButton();
        tbFiltrar = new javax.swing.JToggleButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPoisson = new com.zap.arca.JATable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        plBotoes = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        plCampos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btProbabilidade = new javax.swing.JButton();
        cbCondicao = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        tfResultado = new com.zap.arca.JADecimalFormatField();
        lbCodigo = new javax.swing.JLabel();
        tfCodigo = new com.zap.arca.JATextField();
        tfNumeroTentativas = new com.zap.arca.JATextField(10,0);
        tfMedia = new com.zap.arca.JADecimalFormatField();
        jButton1 = new javax.swing.JButton();
        tfPercentual = new com.zap.arca.JADecimalFormatField();
        lbResultado1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miArquivoSair = new com.zap.arca.JAMenuItem();
        mnEditar = new javax.swing.JMenu();
        miEdiIncluir = new javax.swing.JMenuItem();
        miEdiAlterar = new javax.swing.JMenuItem();
        miEdiExcluir = new javax.swing.JMenuItem();
        miEditarLimpar = new com.zap.arca.JAMenuItem();
        mnExibir = new javax.swing.JMenu();
        miExibirAtualizar = new com.zap.arca.JAMenuItem();
        spExibir = new javax.swing.JPopupMenu.Separator();
        miExibirFiltro = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        miAjudaConteudo = new com.zap.arca.JAMenuItem();
        spAjuda = new javax.swing.JPopupMenu.Separator();
        miAjudaSobre = new com.zap.arca.JAMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Poisson");

        tbAtalhos.setFloatable(false);
        tbAtalhos.setRollover(true);

        bgEditar.add(tbIncluir);
        tbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/add.png"))); // NOI18N
        tbIncluir.setToolTipText("Incluir");
        tbIncluir.setFocusable(false);
        tbIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIncluirActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbIncluir);

        bgEditar.add(tbAlterar);
        tbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/edit.png"))); // NOI18N
        tbAlterar.setToolTipText("Alterar");
        tbAlterar.setFocusable(false);
        tbAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAlterarActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbAlterar);

        bgEditar.add(tbExcluir);
        tbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/delete.png"))); // NOI18N
        tbExcluir.setFocusable(false);
        tbExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExcluirActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbExcluir);
        tbAtalhos.add(spBar);

        bgEditar.add(tbPesquisar);
        tbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/pesquisar.png"))); // NOI18N
        tbPesquisar.setFocusable(false);
        tbPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPesquisarActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbPesquisar);

        bgEditar.add(tbFiltrar);
        tbFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/filter.png"))); // NOI18N
        tbFiltrar.setFocusable(false);
        tbFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbFiltrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFiltrarActionPerformed(evt);
            }
        });
        tbAtalhos.add(tbFiltrar);

        jSplitPane1.setDividerLocation(110);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tbPoisson.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPoisson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPoisson);
        tbPoisson.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                alterar(tbPoisson);
            }
        });

        jSplitPane1.setTopComponent(jScrollPane1);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plBotoesLayout = new javax.swing.GroupLayout(plBotoes);
        plBotoes.setLayout(plBotoesLayout);
        plBotoesLayout.setHorizontalGroup(
            plBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plBotoesLayout.createSequentialGroup()
                .addContainerGap(544, Short.MAX_VALUE)
                .addComponent(btOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancelar)
                .addGap(6, 6, 6))
        );

        plBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCancelar, btOk});

        plBotoesLayout.setVerticalGroup(
            plBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btOk)
                .addComponent(btCancelar))
        );

        plCampos.setBackground(new java.awt.Color(255, 255, 255));
        plCampos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fórmula"));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/poisson.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/media.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Média (K):");

        jLabel5.setText("Número de Tentativas(X):");

        btProbabilidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/select.png"))); // NOI18N
        btProbabilidade.setToolTipText("Calcular Probabilidade");
        btProbabilidade.setOpaque(false);
        btProbabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProbabilidadeActionPerformed(evt);
            }
        });

        cbCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCondicaoActionPerformed(evt);
            }
        });
        cbCondicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbCondicaoFocusLost(evt);
            }
        });

        jLabel7.setText("Condição:");

        lbResultado.setText("Resultado:");

        tfResultado.setEnabled(false);
        tfResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoActionPerformed(evt);
            }
        });

        lbCodigo.setText("Código:");

        tfCodigo.setEnabled(false);

        tfNumeroTentativas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("CALCULAR");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfPercentual.setEnabled(false);
        tfPercentual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfPercentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPercentualActionPerformed(evt);
            }
        });

        lbResultado1.setText("Percentual:");

        jLabel3.setText("%");

        javax.swing.GroupLayout plCamposLayout = new javax.swing.GroupLayout(plCampos);
        plCampos.setLayout(plCamposLayout);
        plCamposLayout.setHorizontalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lbCodigo)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(lbResultado))
                        .addGap(10, 10, 10)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfNumeroTentativas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCondicao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addComponent(btProbabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plCamposLayout.createSequentialGroup()
                                .addComponent(lbResultado1)
                                .addGap(79, 79, 79)
                                .addComponent(tfPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        plCamposLayout.setVerticalGroup(
            plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plCamposLayout.createSequentialGroup()
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumeroTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btProbabilidade)
                            .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResultado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(plCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResultado1)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tfCodigo.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                // verificaAlteracao();
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
            public void changedUpdate(DocumentEvent e) { }
            public void removeUpdate(DocumentEvent e) {
                //verificaAlteracao();
                if(tfCodigo.getText().equals("")) {
                    tbAlterar.setSelected(false);
                    tbIncluir.setSelected(true);
                } else {
                    tbAlterar.setSelected(true);
                    tbIncluir.setSelected(false);
                }
            }
        });

        jTabbedPane1.addTab("Poisson", plCampos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("<html> x = n° designado de sucesso<br><br> k = n° médio de sucessos num intervalo específico<br><br> e = base do logaritmo natural (2,71828) </html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajuda", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        jSplitPane1.setRightComponent(jScrollPane2);

        mnArquivo.setText("Arquivo");

        miArquivoSair.setText("Sair");
        miArquivoSair.setPreferredSize(new java.awt.Dimension(120, 22));
        miArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miArquivoSairActionPerformed(evt);
            }
        });
        mnArquivo.add(miArquivoSair);

        mbPrincipal.add(mnArquivo);

        mnEditar.setText("Editar");

        miEdiIncluir.setText("Incluir");
        miEdiIncluir.setPreferredSize(new java.awt.Dimension(120, 22));
        miEdiIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEdiIncluirActionPerformed(evt);
            }
        });
        mnEditar.add(miEdiIncluir);

        miEdiAlterar.setText("Alterar");
        miEdiAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEdiAlterarActionPerformed(evt);
            }
        });
        mnEditar.add(miEdiAlterar);

        miEdiExcluir.setText("Excluir");
        miEdiExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEdiExcluirActionPerformed(evt);
            }
        });
        mnEditar.add(miEdiExcluir);

        miEditarLimpar.setText("Limpar");
        miEditarLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarLimparActionPerformed(evt);
            }
        });
        mnEditar.add(miEditarLimpar);

        mbPrincipal.add(mnEditar);

        mnExibir.setText("Exibir");

        miExibirAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        miExibirAtualizar.setText("Atualizar");
        miExibirAtualizar.setPreferredSize(new java.awt.Dimension(150, 22));
        miExibirAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExibirAtualizarActionPerformed(evt);
            }
        });
        mnExibir.add(miExibirAtualizar);
        mnExibir.add(spExibir);

        miExibirFiltro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        miExibirFiltro.setText("Filtro...");
        miExibirFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExibirFiltroActionPerformed(evt);
            }
        });
        mnExibir.add(miExibirFiltro);

        mbPrincipal.add(mnExibir);

        mnAjuda.setText("Ajuda");

        miAjudaConteudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miAjudaConteudo.setText("Conteúdo da Ajuda");
        mnAjuda.add(miAjudaConteudo);
        mnAjuda.add(spAjuda);

        miAjudaSobre.setText("Sobre...");
        miAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjudaSobreActionPerformed(evt);
            }
        });
        mnAjuda.add(miAjudaSobre);

        mbPrincipal.add(mnAjuda);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
            .addComponent(tbAtalhos, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if (verificarCampos(camposVerificar)) {
            inserirOuAlterar();
            limparCampos();
        }
        actionMenu(INCLUSAO);
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tbIncluirActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_tbIncluirActionPerformed
        actionMenu(INCLUSAO);
     }//GEN-LAST:event_tbIncluirActionPerformed

    private void tbAlterarActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_tbAlterarActionPerformed
        actionMenu(ALTERACAO);
     }//GEN-LAST:event_tbAlterarActionPerformed

    private void miArquivoSairActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miArquivoSairActionPerformed
        this.dispose();
     }//GEN-LAST:event_miArquivoSairActionPerformed

    private void miEdiIncluirActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEdiIncluirActionPerformed
        actionMenu(INCLUSAO);
     }//GEN-LAST:event_miEdiIncluirActionPerformed

    private void miEdiAlterarActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEdiAlterarActionPerformed
        actionMenu(ALTERACAO);
     }//GEN-LAST:event_miEdiAlterarActionPerformed

    private void miEdiExcluirActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEdiExcluirActionPerformed
        actionMenu(EXCLUSAO);
     }//GEN-LAST:event_miEdiExcluirActionPerformed

    private void miExibirAtualizarActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miExibirAtualizarActionPerformed
        actionMenu(LIMPAR);
     }//GEN-LAST:event_miExibirAtualizarActionPerformed

    private void miExibirFiltroActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miExibirFiltroActionPerformed
        actionMenu(FILTRAR);
     }//GEN-LAST:event_miExibirFiltroActionPerformed

    private void miEditarLimparActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miEditarLimparActionPerformed
        actionMenu(LIMPAR);
    }//GEN-LAST:event_miEditarLimparActionPerformed

    private void miAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjudaSobreActionPerformed
    }//GEN-LAST:event_miAjudaSobreActionPerformed

    private void tbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExcluirActionPerformed
        actionMenu(EXCLUSAO);
    }//GEN-LAST:event_tbExcluirActionPerformed

    private void tbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPesquisarActionPerformed
        actionMenu(PESQUISAR);
    }//GEN-LAST:event_tbPesquisarActionPerformed

    private void tbFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFiltrarActionPerformed
        actionMenu(FILTRAR);
    }//GEN-LAST:event_tbFiltrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tfResultado.setValue(calcular().doubleValue());
        tfPercentual.setValue(calcular()*100);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoActionPerformed
    }//GEN-LAST:event_tfResultadoActionPerformed

    private void cbCondicaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbCondicaoFocusLost
    }//GEN-LAST:event_cbCondicaoFocusLost

    private void cbCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCondicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCondicaoActionPerformed

    private void btProbabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProbabilidadeActionPerformed
        new DMedia(this, true).setVisible(true);
    }//GEN-LAST:event_btProbabilidadeActionPerformed

    private void tfPercentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPercentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPercentualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPoisson().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEditar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btProbabilidade;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbCondicao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbResultado1;
    private javax.swing.JMenuBar mbPrincipal;
    private com.zap.arca.JAMenuItem miAjudaConteudo;
    private com.zap.arca.JAMenuItem miAjudaSobre;
    private com.zap.arca.JAMenuItem miArquivoSair;
    private javax.swing.JMenuItem miEdiAlterar;
    private javax.swing.JMenuItem miEdiExcluir;
    private javax.swing.JMenuItem miEdiIncluir;
    private com.zap.arca.JAMenuItem miEditarLimpar;
    private com.zap.arca.JAMenuItem miExibirAtualizar;
    private javax.swing.JMenuItem miExibirFiltro;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnEditar;
    private javax.swing.JMenu mnExibir;
    private javax.swing.JPanel plBotoes;
    private javax.swing.JPanel plCampos;
    private javax.swing.JPopupMenu.Separator spAjuda;
    private javax.swing.JToolBar.Separator spBar;
    private javax.swing.JPopupMenu.Separator spExibir;
    private javax.swing.JToggleButton tbAlterar;
    private javax.swing.JToolBar tbAtalhos;
    private javax.swing.JToggleButton tbExcluir;
    private javax.swing.JToggleButton tbFiltrar;
    private javax.swing.JToggleButton tbIncluir;
    private javax.swing.JToggleButton tbPesquisar;
    private com.zap.arca.JATable tbPoisson;
    private com.zap.arca.JATextField tfCodigo;
    private com.zap.arca.JADecimalFormatField tfMedia;
    private com.zap.arca.JATextField tfNumeroTentativas;
    private com.zap.arca.JADecimalFormatField tfPercentual;
    private com.zap.arca.JADecimalFormatField tfResultado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciar() {
        dao = new DAOPoisson();

        tbPrincipal = tbPoisson;
        toggleButton = tbIncluir;
        ctChave = tfCodigo;

        tbPoisson.setName("TB_FPOISSON");
        tbPoisson.setModel(poissonTableModel);

        camposVerificar = new Component[]{tfNumeroTentativas, tfMedia};
        camposLimpar = new Component[]{tfNumeroTentativas, tfMedia, tfCodigo, tfResultado, tfPercentual};

        WindowUtils.nextEnter(plCampos);
        WindowUtils.exitEsc(this);
        configurarSincronizacao(dao, tbPoisson);
        carregarCombo();
    }

    public void carregarCombo() {
        for (Binomial.Condicao condicao : Binomial.Condicao.values()) {
            cbCondicao.addItem(condicao.toString());
        }
    }

    public Poisson.Condicao getCondicao() {
        if (cbCondicao.getSelectedIndex() == 0) {
            return Poisson.Condicao.MAIOR;
        } else if (cbCondicao.getSelectedIndex() == 1) {
            return Poisson.Condicao.MENOR;
        } else if (cbCondicao.getSelectedIndex() == 2) {
            return Poisson.Condicao.MAIOR_E_IGUAL;
        } else if (cbCondicao.getSelectedIndex() == 3) {
            return Poisson.Condicao.MENOR_E_IGUAL;
        } else {
            return Poisson.Condicao.IGUAL;
        }
    }

    public Double calcular() {
        int tentativas = tfNumeroTentativas.intValue();
        Calculo c = new Calculo();
        double media = tfMedia.getValue().doubleValue();
        double resultado = 0.0;
        if (cbCondicao.getSelectedIndex() == 0) {
            for (int i = tentativas; i >= 0; i--) {
                resultado += c.Px(i, media);
            }
            return 1 - resultado;
        } else if (cbCondicao.getSelectedIndex() == 1) {
            for (int i = tentativas - 1; i >= 0; i--) {
                resultado += c.Px(i, media);
            }
            return resultado;
        } else if (cbCondicao.getSelectedIndex() == 2) {
            for (int i = tentativas-1; i >= 0; i--) {
                resultado += c.Px(i, media);
            }
            return 1 - resultado;
        } else if (cbCondicao.getSelectedIndex() == 3) {
            for (int i = tentativas; i >= 0; i--) {
                resultado += c.Px(i, media);
            }
            return resultado;
        } else if (cbCondicao.getSelectedIndex() == 4) {
            return c.Px(tentativas, media);
        }
        return null;
    }

    public void setCondicao(Poisson.Condicao condicao) {
        switch (condicao) {
            case MAIOR:
                cbCondicao.setSelectedIndex(0);
                break;
            case MENOR:
                cbCondicao.setSelectedIndex(1);
                break;
            case MAIOR_E_IGUAL:
                cbCondicao.setSelectedIndex(2);
                break;
            case MENOR_E_IGUAL:
                cbCondicao.setSelectedIndex(3);
                break;
            case IGUAL:
                cbCondicao.setSelectedIndex(4);
                break;
        }
    }

    @Override
    public void inserirOuAlterar() {
        poisson = new Poisson();
        poisson.setMedia(tfMedia.getValue().doubleValue());
        poisson.setTentativas(tfNumeroTentativas.intValue());
        poisson.setResultado(tfResultado.getValue().doubleValue());
        poisson.setCondicao(getCondicao());
        poisson.setPercentual(tfPercentual.getValue().doubleValue());
        try {
            if (tbAlterar.isSelected()) {
                poisson.setCodigo(Integer.valueOf(tfCodigo.getText()));
                dao.alterar(poisson);
                JOptionPane.showMessageDialog(null, DAOGenerico.M_ALTERAR);
            } else {
                dao.adicionar(poisson);
                JOptionPane.showMessageDialog(null, DAOGenerico.M_ADICIONAR); 
            }
        } catch (RuntimeException ex) {
            LoggerEx.log(ex);
        }
    }

    @Override
    public void preencherCampos(IModelo m) {
        poisson = (Poisson) m;
        tfCodigo.setText(poisson.getCodigo() + "");
        tfNumeroTentativas.setText(poisson.getTentativas() + "");
        tfMedia.setValue(poisson.getMedia().doubleValue());
        tfResultado.setValue(poisson.getResultado().doubleValue());
        tfPercentual.setValue(poisson.getPercentual()!=null?poisson.getPercentual().doubleValue():BigDecimal.ZERO.doubleValue());
        setCondicao(poisson.getCondicao());
    }

    @Override
    public void preencherTabela(int linha, IModelo i) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setValor(BigDecimal probabilidade) {
        tfMedia.setValue(probabilidade.doubleValue());
    }

    public void formatarCampos() {
        tfResultado.setTotalCasas(5, 8);
        tfMedia.setTotalCasas(5, 8);
    }
}
